In [100]:
import numpy as np
import pandas as pd

In [101]:
A=np.array([2,3],dtype=int)

In [102]:
A

array([2, 3])

In [103]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
a=np.arange(1,10,2)

In [106]:
a

array([1, 3, 5, 7, 9])

In [107]:
a=np.arange(12).reshape((3,4))

In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a=np.linspace(1,20,2)

In [110]:
a=np.array([[1,2,3],[4,5,6]])

In [111]:
a.shape

(2, 3)

In [112]:
a.size

6

In [113]:
a[1].size

3

In [114]:
a=np.linspace(1,20,10)



In [115]:
a

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [116]:
a=np.array([1,2,3])

In [117]:
10*np.sin(a)

array([8.41470985, 9.09297427, 1.41120008])

In [118]:
b=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [119]:
c=a*b

In [120]:
c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [121]:
b.dot(a)

array([1, 2, 3])

In [122]:
a@b

array([1, 2, 3])

In [123]:
np.sum(b,axis=1)#1是行，0是列

array([1, 1, 1])

In [124]:
np.sum(a,axis=0)

6

In [125]:
np.transpose(a)

array([1, 2, 3])

In [126]:
a=np.arange(15)

In [127]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array 的位置索引

In [128]:
a[3]

3

In [129]:
A=np.arange(3,15).reshape((3,4))

In [130]:
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [131]:
A[2]#在索引特的行数

array([11, 12, 13, 14])

In [132]:
A[1][1]

8

In [133]:
A[2][1]

12

In [134]:
A[2,1]

12

In [135]:
A[:,1]

array([ 4,  8, 12])

In [136]:
A[1:,2:4]

array([[ 9, 10],
       [13, 14]])

In [137]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


对列进行迭代

In [138]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [139]:
for item in A.flat:
    print(item)#对矩阵的每一个项都打印出来

3
4
5
6
7
8
9
10
11
12
13
14


合并两个array

In [140]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [141]:
B=np.array([[10,11,12],[13,14,15],[16,17,18]])

In [142]:
C=np.vstack((A,B))#上下合并

In [143]:
C

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [144]:
A.shape

(3, 3)

In [145]:
B.shape

(3, 3)

In [146]:
C.shape

(6, 3)

In [147]:
D=np.hstack((A,B))#左右合并

In [148]:
D

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [149]:
f= D.T

In [150]:
D.shape

(3, 6)

In [151]:
f.shape

(6, 3)

In [152]:
np.concatenate((A,B,B,A),axis=1)#横向的合并

array([[ 1,  2,  3, 10, 11, 12, 10, 11, 12,  1,  2,  3],
       [ 4,  5,  6, 13, 14, 15, 13, 14, 15,  4,  5,  6],
       [ 7,  8,  9, 16, 17, 18, 16, 17, 18,  7,  8,  9]])

In [153]:
np.concatenate((A,B),axis=0)#纵向的合并

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [154]:
A= np.arange(12).reshape((3,4))

In [155]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
np.split(A,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [157]:
np.split(A,4,axis=1)#1是对列分割

[array([[0],
        [4],
        [8]]), array([[1],
        [5],
        [9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

不等量的分割

In [158]:
np.array_split(A,3,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [159]:
np.vsplit(A,3)#纵向滓的分割


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [160]:
np.hsplit(A,2)#横向的分割

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [161]:
a=np.arange(4)

In [162]:
a

array([0, 1, 2, 3])

In [163]:
b=a

In [164]:
c=a

In [165]:
d=b

In [166]:
a[1]=12

In [167]:
a

array([ 0, 12,  2,  3])

In [168]:
b

array([ 0, 12,  2,  3])

In [169]:
b is a

True

In [170]:
d is b

True

In [171]:
d is a

True

In [172]:
b=a.copy()#只是把
的值给b，修改a并不会改变b的值

SyntaxError: invalid character in identifier (<ipython-input-172-d93287a563be>, line 2)

In [173]:
a

array([ 0, 12,  2,  3])

In [174]:
a[2]=10

In [175]:
a

array([ 0, 12, 10,  3])

In [176]:
b

array([ 0, 12, 10,  3])

In [177]:
A=np.arange(12).reshape((3,4))

In [178]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
A.shape[0]

3

In [182]:
a=np.ones(A.shape[0],A[:,2])

TypeError: data type not understood